# Pydantic schemas for the api/v1/ask endpoint

from typing import List, Optional
from pydantic import BaseModel, Field

# ---------------------------
# Citation Schema
# ---------------------------
# This represents one piece of evidence used to support the RAG answer.
# Every citation tells us where the answer came from.

class Citation(BaseModel):
    source_id: str = Field(..., description="Which source this citation came from")
    chunk_id: Optional[str] = Field(None, description="Optional Chunk Identifier")
    snippet: str = Field(..., description="Short text snippet shown to user")
    start_seconds: Optional[float] = Field(None, description="For YouTube sources, where to jump to")
    url: Optional[str] = Field(None, description="Optional URL to the source, e.g. YouTube video or PDF page")


# ---------------------------
# AskRequest Schema
# ---------------------------
# This defines what the frontend sends to the backend when a user asks a question.

class AskRequest(BaseModel):
    query: str = Field(..., min_length=1, description="User question")
    source_ids: List[str] = Field(default_factory=list, description="Selected sources to search")
    top_k: int = Field(5, ge=1, le=20, description="How many chunks to retrieve")


# ---------------------------
# AskResponse Schema
# ---------------------------
# This defines what the backend sends back to the frontend after processing the question.

class AskResponse(BaseModel):
    answer: str = Field(..., description="Answer generated by the model")
    citations: List[Citation] = Field(default_factory=list, description="Supporting citations")

